project:
  type: book
  output-dir: "_output"

lang: es

book:
  title: "Título del trabajo"
  author: "Nombre y Apellidos"
  date: today
  license: "CC BY 4.0"
  chapters:
    - index.qmd
    - 01-introducción.qmd
    - 02-capítulo2.qmd
    - 03-capítulo3.qmd
    - 04-capítulo4.qmd
    - 05-conclusiones.qmd
    - 06-conclusions.qmd
    - 07-presupuesto.qmd
    - referencias.qmd
  appendices:
    - 0A-apéndice1.qmd
    - 0B-apéndice2.qmd

tfg-report:
  title-en: "Title in English"
  tutors:
    - "Nombre Apellido1 Apellido2"
    - "Nombre Apellido1 Apellido2"
  summary:
    es: resumen.qmd
    en: abstract.qmd

bibliography: referencias.bib

format:
  ull-esit-gii-tfg-pdf:
    # colorlinks: true
    keep-tex: true